from flask import Flask, render_template, request
import random

app = Flask(__name__)
# defining the questions (templates..................)
question_templates = [
    "What are your thoughts on {}?",
    "How do you feel about {}?",
    "Can you explain why {} is important?",
    "What are the benefits of {}?",
    "How does {} impact your daily life?",
    "What challenges have you faced with {}?",
    "What are your favorite things about {}?",
    "Can you describe your experience with {}?",
    "What advice would you give to someone about {}?",
    "How has {} changed over time?",
    "What are some common misconceptions about {}?",
    "How would you improve {}?",
    "What inspired you to start {}?",
    "What are the key factors to consider in {}?",
    "How do you balance {} with other aspects of your life?",
    "What role does {} play in your life?",
    "How do you approach {}?",
    "What do you find most rewarding about {}?",
    "How has {} shaped your perspective?",
    "What are the key trends in {}?",
    "How do you stay updated with {}?",
    "What are some effective strategies for {}?",
    "How do you overcome obstacles in {}?",
    "What future developments do you foresee in {}?",
    "What personal experiences have you had with {}?",
    "How do you see {} evolving in the next decade?",
    "What impact has {} had on society?",
    "What are some innovative ideas related to {}?",
    "How do you integrate {} into your lifestyle?",
    "What historical events influenced {}?",
    "How do you prioritize {} among other activities?",
    "What do you think is the future of {}?",
    "What are the cultural implications of {}?",
    "How does {} affect your community?",
    "What are some challenges with {}?",
    "How can we improve our understanding of {}?",
    "What are the pros and cons of {}?",
    "What motivates you about {}?",
    "What ethical considerations are there with {}?",
    "How do you educate others about {}?",
    "What are some myths about {}?",
    "How can technology enhance {}?",
    "What are your plans for {}?",
    "What are the latest developments in {}?",
    "How do you handle {}?",
    "What are the limitations of {}?",
    "What are the different types of {}?",
    "What are the current trends in {}?",
    "What are your expectations for {}?",
    "What are some strategies to improve {}?",
    "How do you stay motivated with {}?",
    "What are the risks associated with {}?",
    "What are the advantages of {}?",
    "How does {} impact the environment?",
    "What are the key features of {}?",
    "How do you evaluate {}?",
    "What are your concerns regarding {}?",
    "What are the cultural aspects of {}?",
    "What are the future prospects of {}?",
    "How do you prepare for {}?",
    "What are the societal implications of {}?",
    "What are your goals related to {}?",
    "What are the global trends in {}?",
    "What are the ethical issues related to {}?",
    "What are the consequences of {}?",
    "What are the effects of {} on health?",
    "What are the challenges in implementing {}?",
    "How do you measure success with {}?",
    "What are the impacts of {} on the economy?",
    "What are the best practices for {}?",
    "What are your predictions for {}?",
    "What are your experiences with {}?",
    "How do you innovate with {}?",
    "What are your strategies for {}?",
    "What are the benefits and drawbacks of {}?",
    "What are the social implications of {}?",
    "What are your thoughts on the future of {}?",
    "How do you manage {}?",
    "What are your concerns about {}?",
    "What are the opportunities related to {}?",
    "What are the challenges of dealing with {}?",
    "How do you address issues related to {}?",
    "What are the key considerations when dealing with {}?",
    "What are your expectations from {}?",
    "What are the legal aspects of {}?",
    "What are your thoughts on the impact of {}?",
    "How do you see the future of {}?",
    "What are your experiences dealing with {}?",
    "How do you approach challenges with {}?",
    "What are the future challenges of {}?",
    "What are the technological advancements in {}?",
    "How do you adapt to changes in {}?",
    "What are the current issues with {}?",
    "What are the economic implications of {}?",
    "What are the potential benefits of {}?",
    "What are the challenges faced by {}?",
    "What are the innovative solutions for {}?",
    "What are your concerns regarding the future of {}?",
    "What are the implications of {}?",
    "What do you think about the future of {}?",
    "How do you see {} evolving in the next decade?",
    "What are some challenges associated with {}?",
    "What are your experiences with {}?",
    "How do you manage {}?",
    "What are the benefits of understanding {}?",
    "What are the key factors influencing {}?",
    "What impact does {} have on society?",
    "How do you address concerns related to {}?",
    "What are your goals related to {}?",
    "How do you stay motivated with {}?",
    "How would you describe the importance of {}?",
    "What are some misconceptions about {}?",
    "What are the future trends in {}?",
    "How do you integrate {} into your daily routine?",
    "What are the advantages and disadvantages of {}?",
    "What are your thoughts on {} and its impact?",
    "How do you foresee {} changing in the future?",
    "What are the ethical considerations in {}?",
    "How does {} influence your decision-making?",
    "What are some effective strategies for dealing with {}?",
    "What do you think are the key challenges facing {}?",
    "How do you prepare for the challenges of {}?",
    "What is your approach to understanding {}?",
    "What are the implications of technology on {}?",
    "What are the challenges and opportunities in {}?",
    "How do you stay informed about developments in {}?",
    "What are your experiences navigating {}?",
    "What are the cultural aspects related to {}?",
    "How do you prioritize {} in your life?",
    "What are the current issues surrounding {}?",
    "What are your concerns about the future of {}?",
    "How do you see the future of {} shaping up?",
    "What are the main reasons behind {}?",
    "What are some tips for learning about {}?",
    "How do you think {} affects society?",
    "What are the key skills needed for {}?",
    "How do you deal with the challenges posed by {}?",
    "What are the benefits of learning about {}?",
    "How does {} impact the environment?",
    "What are the social implications of {}?",
    "What are the trends in {} that you've noticed?",
    "What are the different perspectives on {}?",
    "What are the consequences of {}?",
    "What are the implications of {} on the economy?",
    "How do you measure success in dealing with {}?",
    "What are your predictions for {}?",
    "What are the future challenges of dealing with {}?",
    "What are the technological advancements related to {}?",
    "How do you adapt to changes in {}?",
    "What are the current issues with {}?"
]

# defining the topics (templates.....................)
topics = [
    "work-life balance",
    "traveling",
    "reading books",
    "cooking",
    "fitness and health",
    "family time",
    "hobbies",
    "music",
    "movies",
    "environmental conservation",
    "volunteering",
    "mental health",
    "self-improvement",
    "social media",
    "photography",
    "gardening",
    "fashion",
    "art",
    "history",
    "science",
    "technology",
    "relationships",
    "pets",
    "sports",
    "education",
    "mindfulness",
    "meditation",
    "career growth",
    "public speaking",
    "financial planning",
    "parenting",
    "travel experiences",
    "personal growth",
    "home improvement",
    "sustainable living",
    "wildlife conservation",
    "urban gardening",
    "culinary arts",
    "cultural traditions",
    "language learning",
    "community building",
    "childhood memories",
    "holiday traditions",
    "storytelling",
    "crafting",
    "virtual reality",
    "digital art",
    "gaming",
    "space exploration",
]

all_combinations = [(template, topic) for template in question_templates for topic in topics]
random.shuffle(all_combinations)

# Generate questions  
questions = [template.format(topic) for template, topic in all_combinations]

# Random questions
def get_random_questions(num_questions):
    return random.sample(questions, num_questions)


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/generate', methods=['POST'])
def generate_questions():
    try:
        num_questions = int(request.form['num_questions'])
        random_questions = get_random_questions(num_questions)
        return render_template('index.html', questions=random_questions, num_questions=num_questions)
    except ValueError:
        return render_template('index.html', error=True)

if __name__ == '__main__':
    app.run(debug=True)
